#!/usr/bin/env python3
"""Pre-fetch Context7 docs listed in topics.txt into .context7-docs/ so Claude reads them locally
instead of spending Context7 requests. Files that already exist are skipped, so re-running is free.

Usage: fetch-docs.py [--force]    (--force re-downloads everything)
"""
import os
import sys
import time
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
TOPICS = Path(__file__).with_name("topics.txt")
OUT = ROOT / ".context7-docs"
API = os.environ.get("CONTEXT7_API_URL", "https://context7.com/api") + "/v2/context"


def topics():
    for line in TOPICS.read_text().splitlines():
        line = line.strip()
        if line and not line.startswith("#"):
            library, file, query = (part.strip() for part in line.split("|", 2))
            yield library, file, query


def fetch(library, query):
    url = API + "?" + urllib.parse.urlencode({"libraryId": library, "query": query})
    headers = {"X-Context7-Source": "prefetch-script"}
    if os.environ.get("CONTEXT7_API_KEY"):
        headers["Authorization"] = "Bearer " + os.environ["CONTEXT7_API_KEY"]
    with urllib.request.urlopen(urllib.request.Request(url, headers=headers), timeout=60) as resp:
        return resp.read().decode(), resp.headers.get("ratelimit-remaining")


def main():
    force = "--force" in sys.argv
    entries = list(topics())
    fetched = skipped = failed = 0
    remaining = None
    for library, file, query in entries:
        target = OUT / file
        if target.exists() and not force:
            skipped += 1
            continue
        try:
            text, remaining = fetch(library, query)
        except urllib.error.HTTPError as e:
            print(f"  ! {file}: HTTP {e.code}", file=sys.stderr)
            failed += 1
            if e.code == 429:
                print("  ! Context7 rate limit reached; re-run later (existing files are kept).", file=sys.stderr)
                break
            continue
        except OSError as e:
            print(f"  ! {file}: {e}", file=sys.stderr)
            failed += 1
            continue
        if not text.strip():
            print(f"  ! {file}: empty response", file=sys.stderr)
            failed += 1
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(f"<!-- context7 {library} | query: {query} | fetched {time.strftime('%Y-%m-%d')} -->\n\n{text}")
        fetched += 1
        print(f"  + {file}")

    write_index(entries)
    left = f", Context7 requests left this period: {remaining}" if remaining else ""
    print(f"Context7 docs: {fetched} fetched, {skipped} cached, {failed} failed{left}")


def write_index(entries):
    OUT.mkdir(exist_ok=True)
    lines = [
        "# Context7 docs cache",
        "",
        "Generated by `.devcontainer/context7/fetch-docs.py` from `.devcontainer/context7/topics.txt`.",
        "Read these files before calling the Context7 MCP.",
        "",
        "| File | Library | Covers |",
        "|---|---|---|",
    ]
    for library, file, query in entries:
        if (OUT / file).exists():
            lines.append(f"| [{file}]({file}) | `{library}` | {query} |")
    (OUT / "INDEX.md").write_text("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
